spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa-relation
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace